config/routes.rb
Onboard::Application.routes.draw do

  get "sessions/new"
# hook up urls with rooms controller
resources :rooms 

# sign up our users to the site
resources :users

# login and logout of our site
# it's a singular resource because we can only do one session
resource :session 

# go to the homepage
root "rooms#index"

end

app/models/room.rb
class Room < ActiveRecord::Base

	# associations
	belongs_to :user

	# this is from the rubygeocoder.org site
	geocoded_by :address
	after_validation :geocode

	# add in paperclip to save images
	# the hash after 960X300 means we crop the image, the titles large + thumbnail could be anything
	# if we want it to be a certain width: "500x"
	# if we wanted it to be a certain height: "x500"
	has_attached_file :image, styles: { 
		large: "960x300#", thumbnail: "50x50#" }  

	# validations
	validates :title, presence: true
	validates :address, presence: true, uniqueness: true
	validates :price, presence: true,
		numericality: { greater_than_or_equal_to: 0.5 }

end

app/models/user.rb
class User < ActiveRecord::Base

	# associations
	has_many :rooms

	# built into rails 4, for handling passwords
	has_secure_password

	# add in paperclip
	has_attached_file :avatar, styles: {
		large: "320x320#",
		medium: "140x140#",
		thumbnail: "50x50#"
	} 

	# validations
	validates :name, presence: true
	validates :username, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # the application controller deals with all of our other
  # controllers like a boss

  # let's make a shortcut called current_user
  def current_user
  	 if session[:user_id].present?
  	 	User.find(session[:user_id])
  	 end
  end

  # make the shortcut above availible in our views
  # aswell as our controllers
  helper_method :current_user

  # let's add in an action to make anyone logged out
  # go to the sign up page

  def make_sure_logged_in
    
    if current_user.nil?
      flash[:error] = "You need to be signed up"
      redirect_to new_user_path
    end
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  # before quite a few of the actions below
  # make sure we're logged in
  before_action :make_sure_logged_in, except: [:index, :show]

  def index
  	@rooms = Room.near("London")

  end

  def show
    @room = Room.find(params[:id])
  end

  def new
  	# the variable @room goes to the view
  	# Room.new comes from the model
  	@room = current_user.rooms.new

  end

  # this is where the form data from the new.html.erb view goes
  def create
  	@room = current_user.rooms.new(room_params)

  	# if the room passes the parameters
  	if @room.save
  		# let's add a flash of content to tell the user
  		# they've succesfully added a room
  		flash[:success] = "You've added your room"

  		# go back to the home page
  		redirect_to root_path
  	else
  		render "new"

  	end
  end

  def edit
    @room = current_user.rooms.find(params[:id])
  end

  def update
    @room = current_user.rooms.find(params[:id])
  	# if updates pass room_params
  	if @room.update(room_params)
  	# show the user it's been successful
		flash[:success] = "You've updated this room"

		# redirect back to the room
		redirect_to room_path(@room)
	   else
		    # otherwise reload the edit page
		    render "edit"

	   end
  end

  def destroy   
    @room =current_user.rooms.find(params[:id])
    @room.destroy
    # show the user it's been successful 
    flash[:success] = "You've deleted this story"
    # redirect back to home page
    redirect_to root_path

  end

  # makes everything below private
  private
  # shortcut for white listing
  def room_params
  	params.require(:room).permit(
  		:title, :address, :description, :max_guests, :bedrooms, :price, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # sessions are the way the browser tracks me
  # we want to manage them in our app
  # sessions controller deals with this stuff

  def new
    # login form
  end

  def create
    # do the login

    # i want to find the username and password typed in
    @username = params[:session][:username]
    @password = params[:session][:password]
    # then i want to see if there's a user with that username
    @user = User.find_by_username(@username)
    # if there is, check their password aswell
    if @user.present? and @user.authenticate(@password)
    # if it matches, give them a session
    session[:user_id] = @user.id
    flash[:success] = "You're logged in"
    redirect_to root_path
    # if not, show the new page
    else
    render "new"
    end
  end

  def destroy
    #aka logout
    reset_session
    flash[:success] = "You've logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	# if the user passes the parameters
  	if @user.save
  		# flash of content to tell the users
  		# they've successfully signed up
  		flash[:success] = "You've successfully signed up!"

  		# we want to keep track of who we've signed up as
  		# in rails we use a thing called a session
  		# this tracks us in the browser using a cookie
  		session[:user_id] = @user.id

  		# go back to home page
  		redirect_to root_path

  	else
  		render "new"
  	end
  end

  # make everything below private
  private
  def user_params
  	# shortcut for white listing form data
  	params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <title>Onboard</title>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <header class="row">
    <h1 class="two columns">
      <%= link_to(root_path) do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </h1>

    <form action="<%= root_path %>" class="three columns">
      <input type="text" name="location">
    </form>

    <nav class="seven columns">

      <% if current_user.present? %>

        <strong><%= current_user.username %></strong>

        <%= link_to "Dashboard", "#" %>
        <%= link_to "Add a room", new_room_path %>
        <%= link_to "Orders", "#" %>
        <%= link_to "Log out", session_path, method: :delete %>

      <% else %>
        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Sign in", new_session_path %>
      <% end %>
    </nav>
  </header>

  <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
  <% end %>

  <article class="row">
    <%= yield %>
  </article>

  <footer>
    <p>&copy; <%= Date.today.year %> Onboard Ltd</p>
  </footer>
</div>

</body>
</html>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>

	<%= form.input :title %>
	<%= form.input :address %>
	<%= form.input :description %>
	<%= form.input :image %>
	<%= form.input :bedrooms %>
	<%= form.input :max_guests %>
	<%= form.input :price %>

	<%= form.button :submit %>

<% end %>

app/views/rooms/edit.html.erb
<%= render "form" %>

app/views/rooms/index.html.erb
<% @rooms.each do |room| %>

	<div class="room">
		<%= link_to room.title, room_path(room) %>
		<%= image_tag room.image(:large) %>
	</div>

<% end %>

<%= link_to "Add a room", new_room_path %>

app/views/rooms/new.html.erb
<%= render "form" %>

app/views/rooms/show.html.erb
<h2><%= @room.title %></h2>

<%= image_tag @room.image(:large) %>

<p><%= @room.address %></p>

<p><%= @room.latitude %><%= @room.longitude %></p>

<div class="actions">
		<%= link_to "Edit", edit_room_path(@room), class: "button" %>
		<%= link_to "Delete", room_path(@room), method: :delete, class: "button", confirm: "Are you sure?" %>
</div>

app/views/users/new.html.erb
<%= simple_form_for @user do |form| %>

	<%= form.input :name %>
	<%= form.input :username %>
	<%= form.input :email %>
	<%= form.input :password %>
	<%= form.input :password_confirmation %>
	<%= form.input :avatar %>

	<%= form.button :submit, "Sign Up" %>

<% end %>